include: package:very_good_analysis/analysis_options.3.1.0.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    inference_failure_on_function_invocation: ignore


linter:
  rules:
    public_member_api_docs: false
