name: doc_prescriptions
version: 1.0.0+1
publish_to: none
description: A Very Good Project created by Very Good CLI.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  intl: ^0.17.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0

dev_dependencies: 
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  generate: true

