name: doc_prescriptions
version: 1.0.1
publish_to: none
description: Doctors Patient Prescription Generator App
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  client_repository:
    path: packages/client_repository
  cloud_firestore: ^4.5.0
  extended_image: ^7.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_keyboard_visibility: ^5.4.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutterfire_ui: ^0.4.3+20
  get: 4.6.5
  get_storage: ^2.1.1
  intl: ^0.17.0
  keyboard_actions: ^4.2.0
  lottie: ^2.3.2
  my_core_pckg:
    path: packages/my_core_pckg
  reactive_forms: ^14.1.0
  simple_animations: ^5.0.0+3
  video_player: ^2.6.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
