name: prescription_repository
description: prescription repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
