// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUCMs-S3Bt9U3mM9V_vdGR3Ei42UUXwoY',
    appId: '1:427479116956:web:de7a339941033ecdce5159',
    messagingSenderId: '427479116956',
    projectId: 'doc-prescribe',
    authDomain: 'doc-prescribe.firebaseapp.com',
    storageBucket: 'doc-prescribe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYB-mU3yqHigwiyPdzLAe_PTuaSgrQcSg',
    appId: '1:427479116956:android:afee9e51d4259196ce5159',
    messagingSenderId: '427479116956',
    projectId: 'doc-prescribe',
    storageBucket: 'doc-prescribe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC4T5ohzEyhvhbtH1IRIgFirSGq-qt1pg',
    appId: '1:427479116956:ios:436cc99aa178a8b2ce5159',
    messagingSenderId: '427479116956',
    projectId: 'doc-prescribe',
    storageBucket: 'doc-prescribe.appspot.com',
    iosClientId:
        '427479116956-iaoojtuhn4p8l6nkqdgp2kggtioibqmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.doc-prescriptions',
  );
}
